name: my-first-gh-workflow # workflow name
on: [push] # triggering event
jobs: # list of jobs
  say-hello: #job name
    runs-on: ubuntu-latest
    steps: #list of steps
      - run: echo Hello Github Actions #step definition
        name: echo step
      - name: checkout step
        uses: actions/checkout@v2 # <- Add this line!!!
      - run: pwd #where are we?
        name: get path step
      - run: ls -la #let's look around
        name: look around step
